      MODULE improvmpi_I
      INTERFACE
!...Generated by Pacific-Sierra Research 77to90  4.3E  16:44:01   1/ 6/07
!...Modified by Charlotte Froese Fischer
!                     Gediminas Gaigalas  10/05/17
      SUBROUTINE improvmpi (EOL, J, LSORT, DAMPMX, PREPARE_ONLY,  &
                            PREPARE_FAILED, FALLBACK_REQUESTED,    &
                            PREPARE_INV, PREPARE_JP, PREPARE_NNP)
      USE vast_kind_param,ONLY: DOUBLE
      LOGICAL, INTENT(IN) :: EOL
      INTEGER, INTENT(IN) :: J
      LOGICAL :: LSORT
      REAL(DOUBLE), INTENT(INOUT) :: DAMPMX
      LOGICAL, INTENT(IN), OPTIONAL :: PREPARE_ONLY
      LOGICAL, INTENT(OUT), OPTIONAL :: PREPARE_FAILED
      LOGICAL, INTENT(OUT), OPTIONAL :: FALLBACK_REQUESTED
      INTEGER, INTENT(OUT), OPTIONAL :: PREPARE_INV, PREPARE_JP
      INTEGER, INTENT(OUT), OPTIONAL :: PREPARE_NNP
      END SUBROUTINE
      END INTERFACE
      END MODULE
