!***********************************************************************
!  Stable CSV diagnostics for optional rmcdhf_mpi orbital tracing.
!  Every event uses the same schema; unused fields are empty.
!***********************************************************************
      MODULE ORBOPT_TRACE_C
      USE vast_kind_param, ONLY: DOUBLE
      USE parameter_def, ONLY: KEYORB
      USE damp_C, ONLY: odamp
      USE fixd_C, ONLY: lfix, nfix
      USE invt_C, ONLY: noinvt
      USE iounit_C, ONLY: istde
      USE mpi_C
      USE eigv_C, ONLY: evec
      USE orb_C, ONLY: nw, np, nh, nak, e
      USE orba_C, ONLY: iorder
      USE corre_C, ONLY: lcorre
      USE scf_C, ONLY: method, scnsty, ucf
      USE wave_C, ONLY: mf, pf, qf
      USE ORBOPT_CONTROL_C
      IMPLICIT NONE

      INTEGER, PARAMETER :: TRACE_FIELD_COUNT = 70
      INTEGER, PARAMETER :: TRACE_FIELD_LENGTH = 128
      LOGICAL :: TRACE_OPEN = .FALSE.

      CONTAINS

      SUBROUTINE OPEN_ORBOPT_TRACE
      CHARACTER(LEN=512) :: TRACE_FILE
      IF (.NOT.TRACE_ORBOPT .OR. myid /= 0 .OR. TRACE_OPEN) RETURN
      TRACE_FILE = 'orbopt_trace.csv'
      IF (LEN_TRIM(ORBOPT_TRACE_DIRECTORY) > 0) TRACE_FILE =       &
         TRIM(ORBOPT_TRACE_DIRECTORY)//'/orbopt_trace.csv'
      OPEN(UNIT=ORBOPT_TRACE_UNIT, FILE=TRIM(TRACE_FILE),           &
           STATUS='REPLACE', ACTION='WRITE')
      CALL WRITE_TRACE_HEADER(ORBOPT_TRACE_UNIT)
      TRACE_OPEN = .TRUE.
      CALL TRACE_ORBOPT_CONTROLS
      END SUBROUTINE OPEN_ORBOPT_TRACE

      SUBROUTINE TRACE_ORBOPT_CONTROLS
      CHARACTER(LEN=TRACE_FIELD_LENGTH) :: FIELDS(TRACE_FIELD_COUNT)
      IF (.NOT.TRACE_OPEN .OR. myid /= 0) RETURN
      CALL CLEAR_TRACE_FIELDS(FIELDS, 'control', 0)
      CALL PUT_REAL(FIELDS(15), FIXED_ORBITAL_DAMPING)
      CALL PUT_REAL(FIELDS(39), MIN_ORBITAL_OVERLAP)
      CALL PUT_REAL(FIELDS(43), MAX_RADIUS_RATIO)
      CALL PUT_INTEGER(FIELDS(47), MAX_REJECTS_PER_ORBITAL)
      CALL PUT_LOGICAL(FIELDS(46), REJECT_NODE_CHANGE)
      CALL PUT_LOGICAL(FIELDS(38), ENABLE_ORBITAL_GUARD)
      CALL PUT_LOGICAL(FIELDS(55), STRICT_SCF_CONVERGENCE)
      CALL PUT_LOGICAL(FIELDS(56), SAVE_RWFN_ITERATIONS)
      CALL PUT_LOGICAL(FIELDS(57), DEFER_ORTHOGONALIZATION)
      CALL PUT_LOGICAL(FIELDS(58), STRICT_METHOD3)
      CALL PUT_LOGICAL(FIELDS(64), ROUND_ROLLBACK_GUARD)
      CALL PUT_LOGICAL(FIELDS(65), ROUND_REJECT_ENERGY_ORDER)
      CALL PUT_REAL(FIELDS(66), MIN_STATE_OVERLAP)
      CALL PUT_INTEGER(FIELDS(67), MAX_ROUND_ROLLBACKS)
      CALL PUT_INTEGER(FIELDS(68), TARGET_STATE_COUNT)
      CALL PUT_LOGICAL(FIELDS(69), TARGET_STATE_COUNT > 1)
      IF (TARGET_STATE_COUNT > 0) THEN
         FIELDS(40) = 'target_states='//TRIM(TARGET_STATE_SPEC)
      ENDIF
      IF (NODE_PROGRESS_GUARD) THEN
         IF (TARGET_STATE_COUNT > 0) THEN
            FIELDS(40) = 'node_guard_progress;target_states='// &
                         TRIM(TARGET_STATE_SPEC)
         ELSE
            FIELDS(40) = 'node_guard_progress'
         ENDIF
      ENDIF
      CALL EMIT_TRACE_ROW(ORBOPT_TRACE_UNIT, FIELDS)
      END SUBROUTINE TRACE_ORBOPT_CONTROLS

      SUBROUTINE CLOSE_ORBOPT_TRACE
      IF (.NOT.TRACE_OPEN .OR. myid /= 0) RETURN
      CLOSE(ORBOPT_TRACE_UNIT)
      TRACE_OPEN = .FALSE.
      END SUBROUTINE CLOSE_ORBOPT_TRACE

      SUBROUTINE WRITE_TRACE_HEADER(UNIT_NUMBER)
      INTEGER, INTENT(IN) :: UNIT_NUMBER
      WRITE (UNIT_NUMBER,'(A)')                                    &
         'event,iteration,rank,index,index2,position,group,np,nh,' // &
         'nak,lfix,lcorre,method,noinvt,odamp,odamp_used,scnsty,' // &
         'energy_old,energy_candidate,dnorm,inv,jp,nnp,fallback,' // &
         'solve_failed,nw,nfix,nsic,nscf,accy,orthst,lsort,wtaev,' // &
         'wtaev0,dampmx,convg_orbital,convg_energy,convg_final,' // &
         'overlap,detail,candidate_norm,old_norm,radius_old,' //   &
         'radius_candidate,nodes_old,nodes_candidate,mf_old,' //   &
         'mtp_candidate,energy_delta,level_weight,convg_legacy,' // &
         'convg_strict,strict_streak,energy_valid,' //             &
         'strict_scf_enabled,save_rwfn_iterations,defer_orthy,' // &
         'strict_method3,round_accepted,round_order_changed,' //   &
         'round_nonidentity,round_rollback_count,round_min_overlap,' // &
         'round_guard_enabled,round_reject_energy_order,' //       &
         'min_state_overlap,max_round_rollbacks,target_state_count,' // &
         'target_order_scoped,round_identity_stable'
      END SUBROUTINE WRITE_TRACE_HEADER

      SUBROUTINE CLEAR_TRACE_FIELDS(FIELDS, EVENT, NIT)
      CHARACTER(LEN=TRACE_FIELD_LENGTH), INTENT(OUT) :: FIELDS(:)
      CHARACTER(LEN=*), INTENT(IN) :: EVENT
      INTEGER, INTENT(IN) :: NIT
      FIELDS = ''
      FIELDS(1) = EVENT
      CALL PUT_INTEGER(FIELDS(2), NIT)
      CALL PUT_INTEGER(FIELDS(3), myid)
      END SUBROUTINE CLEAR_TRACE_FIELDS

      SUBROUTINE EMIT_TRACE_ROW(UNIT_NUMBER, FIELDS)
      INTEGER, INTENT(IN) :: UNIT_NUMBER
      CHARACTER(LEN=TRACE_FIELD_LENGTH), INTENT(IN) :: FIELDS(:)
      INTEGER :: I
      DO I = 1, TRACE_FIELD_COUNT
         ! Detail fields may contain a comma (for example the target-state
         ! specification). Quote such fields so every row remains valid CSV.
         IF (INDEX(TRIM(FIELDS(I)), ',') > 0) THEN
            WRITE (UNIT_NUMBER,'(A)',ADVANCE='NO') &
                 '"'//TRIM(FIELDS(I))//'"'
         ELSE
            WRITE (UNIT_NUMBER,'(A)',ADVANCE='NO') TRIM(FIELDS(I))
         ENDIF
         IF (I < TRACE_FIELD_COUNT)                                 &
            WRITE (UNIT_NUMBER,'(A)',ADVANCE='NO') ','
      END DO
      WRITE (UNIT_NUMBER,'(A)') ''
      END SUBROUTINE EMIT_TRACE_ROW

      SUBROUTINE PUT_INTEGER(FIELD, VALUE)
      CHARACTER(LEN=*), INTENT(OUT) :: FIELD
      INTEGER, INTENT(IN) :: VALUE
      WRITE (FIELD,'(I0)') VALUE
      END SUBROUTINE PUT_INTEGER

      SUBROUTINE PUT_REAL(FIELD, VALUE)
      CHARACTER(LEN=*), INTENT(OUT) :: FIELD
      REAL(DOUBLE), INTENT(IN) :: VALUE
      WRITE (FIELD,'(ES24.16)') VALUE
      FIELD = ADJUSTL(FIELD)
      END SUBROUTINE PUT_REAL

      SUBROUTINE PUT_LOGICAL(FIELD, VALUE)
      CHARACTER(LEN=*), INTENT(OUT) :: FIELD
      LOGICAL, INTENT(IN) :: VALUE
      IF (VALUE) THEN
         FIELD = 'true'
      ELSE
         FIELD = 'false'
      ENDIF
      END SUBROUTINE PUT_LOGICAL

      SUBROUTINE PUT_ORBITAL_FIELDS(FIELDS, J)
      CHARACTER(LEN=TRACE_FIELD_LENGTH), INTENT(INOUT) :: FIELDS(:)
      INTEGER, INTENT(IN) :: J
      CALL PUT_INTEGER(FIELDS(4), J)
      CALL PUT_INTEGER(FIELDS(8), NP(J))
      FIELDS(9) = NH(J)
      CALL PUT_INTEGER(FIELDS(10), NAK(J))
      CALL PUT_LOGICAL(FIELDS(11), LFIX(J))
      CALL PUT_LOGICAL(FIELDS(12), LCORRE(J))
      CALL PUT_INTEGER(FIELDS(13), METHOD(J))
      CALL PUT_LOGICAL(FIELDS(14), NOINVT(J))
      CALL PUT_REAL(FIELDS(15), ODAMP(J))
      CALL PUT_REAL(FIELDS(17), SCNSTY(J))
      END SUBROUTINE PUT_ORBITAL_FIELDS

      SUBROUTINE PUT_ORBITAL_GROUP(FIELD, J)
      CHARACTER(LEN=*), INTENT(OUT) :: FIELD
      INTEGER, INTENT(IN) :: J
      IF (LFIX(J)) THEN
         FIELD = 'fixed'
      ELSE IF (.NOT.LCORRE(J)) THEN
         FIELD = 'spectroscopic'
      ELSE
         FIELD = 'correlation'
      ENDIF
      END SUBROUTINE PUT_ORBITAL_GROUP

      SUBROUTINE TRACE_ORBITAL_SELECTION
      CHARACTER(LEN=TRACE_FIELD_LENGTH) :: FIELDS(TRACE_FIELD_COUNT)
      INTEGER :: I
      CALL OPEN_ORBOPT_TRACE
      IF (.NOT.TRACE_OPEN) RETURN
      DO I = 1, NW
         CALL CLEAR_TRACE_FIELDS(FIELDS, 'selection', 0)
         CALL PUT_ORBITAL_FIELDS(FIELDS, I)
         CALL PUT_INTEGER(FIELDS(6), IORDER(I))
         CALL PUT_ORBITAL_GROUP(FIELDS(7), I)
         CALL PUT_REAL(FIELDS(19), E(I))
         CALL PUT_INTEGER(FIELDS(26), NW)
         CALL PUT_INTEGER(FIELDS(27), NFIX)
         CALL EMIT_TRACE_ROW(ORBOPT_TRACE_UNIT, FIELDS)
      END DO
      END SUBROUTINE TRACE_ORBITAL_SELECTION

      SUBROUTINE TRACE_SCF_BEGIN(NIT, NSCF, NSIC, ACCY, ORTHST,     &
                                 LSORT, WTAEV0)
      INTEGER, INTENT(IN) :: NIT, NSCF, NSIC
      REAL(DOUBLE), INTENT(IN) :: ACCY, WTAEV0
      LOGICAL, INTENT(IN) :: ORTHST, LSORT
      CHARACTER(LEN=TRACE_FIELD_LENGTH) :: FIELDS(TRACE_FIELD_COUNT)
      CALL OPEN_ORBOPT_TRACE
      IF (.NOT.TRACE_OPEN) RETURN
      CALL CLEAR_TRACE_FIELDS(FIELDS, 'scf_begin', NIT)
      CALL PUT_INTEGER(FIELDS(26), NW)
      CALL PUT_INTEGER(FIELDS(27), NFIX)
      CALL PUT_INTEGER(FIELDS(28), NSIC)
      CALL PUT_INTEGER(FIELDS(29), NSCF)
      CALL PUT_REAL(FIELDS(30), ACCY)
      CALL PUT_LOGICAL(FIELDS(31), ORTHST)
      CALL PUT_LOGICAL(FIELDS(32), LSORT)
      CALL PUT_REAL(FIELDS(34), WTAEV0)
      CALL EMIT_TRACE_ROW(ORBOPT_TRACE_UNIT, FIELDS)
      END SUBROUTINE TRACE_SCF_BEGIN

      SUBROUTINE TRACE_ORBITAL_UPDATE(STAGE, NIT, J, EOLD, ECAND,   &
                                      DNORM, ODAMP_USED, INV, JP,   &
                                      NNP, FALLBACK, FAIL, DETAIL)
      CHARACTER(LEN=*), INTENT(IN) :: STAGE
      INTEGER, INTENT(IN) :: NIT, J, INV, JP, NNP
      REAL(DOUBLE), INTENT(IN) :: EOLD, ECAND, DNORM, ODAMP_USED
      LOGICAL, INTENT(IN) :: FALLBACK, FAIL
      CHARACTER(LEN=*), INTENT(IN), OPTIONAL :: DETAIL
      CHARACTER(LEN=TRACE_FIELD_LENGTH) :: FIELDS(TRACE_FIELD_COUNT)
      INTEGER :: TRACE_NIT
      CALL OPEN_ORBOPT_TRACE
      IF (.NOT.TRACE_OPEN) RETURN
      TRACE_NIT = NIT
      IF (TRACE_NIT == 0) TRACE_NIT = ORBOPT_ITERATION
      CALL CLEAR_TRACE_FIELDS(FIELDS, STAGE, TRACE_NIT)
      CALL PUT_ORBITAL_FIELDS(FIELDS, J)
      CALL PUT_ORBITAL_GROUP(FIELDS(7), J)
      CALL PUT_REAL(FIELDS(18), EOLD)
      CALL PUT_REAL(FIELDS(19), ECAND)
      IF (STAGE /= 'solve_result') CALL PUT_REAL(FIELDS(20), DNORM)
      IF (STAGE == 'accepted' .OR. STAGE == 'rejected')            &
         CALL PUT_REAL(FIELDS(16), ODAMP_USED)
      CALL PUT_INTEGER(FIELDS(21), INV)
      CALL PUT_INTEGER(FIELDS(22), JP)
      CALL PUT_INTEGER(FIELDS(23), NNP)
      CALL PUT_LOGICAL(FIELDS(24), FALLBACK)
      CALL PUT_LOGICAL(FIELDS(25), FAIL)
      IF (PRESENT(DETAIL)) FIELDS(40) = DETAIL
      CALL EMIT_TRACE_ROW(ORBOPT_TRACE_UNIT, FIELDS)
      END SUBROUTINE TRACE_ORBITAL_UPDATE

      SUBROUTINE TRACE_ORBITAL_METRICS(NIT, J, CANDIDATE_NORM,     &
            OLD_NORM, OVERLAP, RADIUS_OLD, RADIUS_CANDIDATE,       &
            NODES_OLD, NODES_CANDIDATE, MF_OLD, MTP_CANDIDATE,    &
            ENERGY_DELTA, EVENT_NAME)
      INTEGER, INTENT(IN) :: NIT, J, NODES_OLD, NODES_CANDIDATE
      INTEGER, INTENT(IN) :: MF_OLD, MTP_CANDIDATE
      REAL(DOUBLE), INTENT(IN) :: CANDIDATE_NORM, OLD_NORM, OVERLAP
      REAL(DOUBLE), INTENT(IN) :: RADIUS_OLD, RADIUS_CANDIDATE
      REAL(DOUBLE), INTENT(IN) :: ENERGY_DELTA
      CHARACTER(LEN=*), INTENT(IN), OPTIONAL :: EVENT_NAME
      CHARACTER(LEN=TRACE_FIELD_LENGTH) :: FIELDS(TRACE_FIELD_COUNT)
      CHARACTER(LEN=TRACE_FIELD_LENGTH) :: METRIC_EVENT
      INTEGER :: TRACE_NIT
      CALL OPEN_ORBOPT_TRACE
      IF (.NOT.TRACE_OPEN) RETURN
      TRACE_NIT = NIT
      IF (TRACE_NIT == 0) TRACE_NIT = ORBOPT_ITERATION
      METRIC_EVENT = 'orbital_metrics'
      IF (PRESENT(EVENT_NAME)) METRIC_EVENT = EVENT_NAME
      CALL CLEAR_TRACE_FIELDS(FIELDS, TRIM(METRIC_EVENT), TRACE_NIT)
      CALL PUT_ORBITAL_FIELDS(FIELDS, J)
      CALL PUT_ORBITAL_GROUP(FIELDS(7), J)
      CALL PUT_REAL(FIELDS(39), OVERLAP)
      CALL PUT_REAL(FIELDS(41), CANDIDATE_NORM)
      CALL PUT_REAL(FIELDS(42), OLD_NORM)
      CALL PUT_REAL(FIELDS(43), RADIUS_OLD)
      CALL PUT_REAL(FIELDS(44), RADIUS_CANDIDATE)
      CALL PUT_INTEGER(FIELDS(45), NODES_OLD)
      CALL PUT_INTEGER(FIELDS(46), NODES_CANDIDATE)
      CALL PUT_INTEGER(FIELDS(47), MF_OLD)
      CALL PUT_INTEGER(FIELDS(48), MTP_CANDIDATE)
      CALL PUT_REAL(FIELDS(49), ENERGY_DELTA)
      CALL EMIT_TRACE_ROW(ORBOPT_TRACE_UNIT, FIELDS)
      END SUBROUTINE TRACE_ORBITAL_METRICS

      SUBROUTINE TRACE_LAGRANGE_PAIRS(NIT, NEC, IECC)
      INTEGER, INTENT(IN) :: NIT, NEC
      INTEGER, INTENT(IN) :: IECC(*)
      CHARACTER(LEN=TRACE_FIELD_LENGTH) :: FIELDS(TRACE_FIELD_COUNT)
      INTEGER :: I, J, K, PAIR, TRACE_NIT
      CALL OPEN_ORBOPT_TRACE
      IF (.NOT.TRACE_OPEN) RETURN
      TRACE_NIT = NIT
      IF (TRACE_NIT == 0) TRACE_NIT = ORBOPT_ITERATION
      DO I = 1, NEC
         PAIR = IECC(I)
         J = PAIR/KEYORB
         K = PAIR - KEYORB*J
         CALL CLEAR_TRACE_FIELDS(FIELDS, 'lagrange_pair', TRACE_NIT)
         CALL PUT_INTEGER(FIELDS(4), K)
         CALL PUT_INTEGER(FIELDS(5), J)
         CALL PUT_INTEGER(FIELDS(6), I)
         WRITE (FIELDS(40),'(A,I0,A,A,I0,A)')                      &
            'left=', NP(K), NH(K), ' right=', NP(J), NH(J)
         CALL EMIT_TRACE_ROW(ORBOPT_TRACE_UNIT, FIELDS)
      END DO
      END SUBROUTINE TRACE_LAGRANGE_PAIRS

      SUBROUTINE TRACE_ORTHY_ORDER(NIT, NAKJ, KTOTAL, KINDX)
      INTEGER, INTENT(IN) :: NIT, NAKJ, KTOTAL
      INTEGER, INTENT(IN) :: KINDX(*)
      CHARACTER(LEN=TRACE_FIELD_LENGTH) :: FIELDS(TRACE_FIELD_COUNT)
      INTEGER :: I, J, TRACE_NIT
      CALL OPEN_ORBOPT_TRACE
      IF (.NOT.TRACE_OPEN) RETURN
      TRACE_NIT = NIT
      IF (TRACE_NIT == 0) TRACE_NIT = ORBOPT_ITERATION
      DO I = 1, KTOTAL
         J = KINDX(I)
         CALL CLEAR_TRACE_FIELDS(FIELDS, 'orthy_order', TRACE_NIT)
         CALL PUT_ORBITAL_FIELDS(FIELDS, J)
         CALL PUT_INTEGER(FIELDS(6), I)
         CALL PUT_ORBITAL_GROUP(FIELDS(7), J)
         CALL PUT_INTEGER(FIELDS(10), NAKJ)
         CALL PUT_REAL(FIELDS(19), E(J))
         CALL EMIT_TRACE_ROW(ORBOPT_TRACE_UNIT, FIELDS)
      END DO
      END SUBROUTINE TRACE_ORTHY_ORDER

      SUBROUTINE TRACE_ORTHY_PROJECTION(NIT, POSITION, L, K, OVRLAP)
      INTEGER, INTENT(IN) :: NIT, POSITION, L, K
      REAL(DOUBLE), INTENT(IN) :: OVRLAP
      CHARACTER(LEN=TRACE_FIELD_LENGTH) :: FIELDS(TRACE_FIELD_COUNT)
      INTEGER :: TRACE_NIT
      CALL OPEN_ORBOPT_TRACE
      IF (.NOT.TRACE_OPEN) RETURN
      TRACE_NIT = NIT
      IF (TRACE_NIT == 0) TRACE_NIT = ORBOPT_ITERATION
      CALL CLEAR_TRACE_FIELDS(FIELDS, 'orthy_projection', TRACE_NIT)
      CALL PUT_ORBITAL_FIELDS(FIELDS, L)
      CALL PUT_INTEGER(FIELDS(5), K)
      CALL PUT_INTEGER(FIELDS(6), POSITION)
      CALL PUT_ORBITAL_GROUP(FIELDS(7), L)
      CALL PUT_REAL(FIELDS(39), OVRLAP)
      CALL EMIT_TRACE_ROW(ORBOPT_TRACE_UNIT, FIELDS)
      END SUBROUTINE TRACE_ORTHY_PROJECTION

      SUBROUTINE TRACE_SCF_END(NIT, CONVG_ORBITAL, CONVG_ENERGY,   &
                               CONVG_LEGACY, CONVG_STRICT,          &
                               CONVG_FINAL, ENERGY_VALID,           &
                               STRICT_STREAK, ROUND_IDENTITY_STABLE,&
                               WTAEV, WTAEV0, DAMPMX)
      INTEGER, INTENT(IN) :: NIT, STRICT_STREAK
      LOGICAL, INTENT(IN) :: CONVG_ORBITAL, CONVG_ENERGY
      LOGICAL, INTENT(IN) :: CONVG_LEGACY, CONVG_STRICT
      LOGICAL, INTENT(IN) :: CONVG_FINAL, ENERGY_VALID
      LOGICAL, INTENT(IN) :: ROUND_IDENTITY_STABLE
      REAL(DOUBLE), INTENT(IN) :: WTAEV, WTAEV0, DAMPMX
      CHARACTER(LEN=TRACE_FIELD_LENGTH) :: FIELDS(TRACE_FIELD_COUNT)
      CALL OPEN_ORBOPT_TRACE
      IF (.NOT.TRACE_OPEN) RETURN
      CALL CLEAR_TRACE_FIELDS(FIELDS, 'scf_end', NIT)
      CALL PUT_REAL(FIELDS(33), WTAEV)
      CALL PUT_REAL(FIELDS(34), WTAEV0)
      CALL PUT_REAL(FIELDS(35), DAMPMX)
      CALL PUT_LOGICAL(FIELDS(36), CONVG_ORBITAL)
      CALL PUT_LOGICAL(FIELDS(37), CONVG_ENERGY)
      CALL PUT_LOGICAL(FIELDS(38), CONVG_FINAL)
      CALL PUT_LOGICAL(FIELDS(51), CONVG_LEGACY)
      CALL PUT_LOGICAL(FIELDS(52), CONVG_STRICT)
      CALL PUT_INTEGER(FIELDS(53), STRICT_STREAK)
      CALL PUT_LOGICAL(FIELDS(54), ENERGY_VALID)
      CALL PUT_LOGICAL(FIELDS(70), ROUND_IDENTITY_STABLE)
      IF (.NOT.CONVG_FINAL) THEN
         FIELDS(40) = 'continue'
      ELSE IF (STRICT_SCF_CONVERGENCE) THEN
         FIELDS(40) = 'strict_two_consecutive'
      ELSE IF (CONVG_ORBITAL) THEN
         FIELDS(40) = 'orbital'
      ELSE
         FIELDS(40) = 'energy'
      ENDIF
      CALL EMIT_TRACE_ROW(ORBOPT_TRACE_UNIT, FIELDS)
      END SUBROUTINE TRACE_SCF_END

      SUBROUTINE TRACE_ROUND_DECISION(NIT, ACCEPTED, MIN_OVERLAP, &
                                      ORDER_CHANGED, NONIDENTITY, &
                                      ROLLBACK_COUNT, DETAIL)
      INTEGER, INTENT(IN) :: NIT, ROLLBACK_COUNT
      LOGICAL, INTENT(IN) :: ACCEPTED, ORDER_CHANGED, NONIDENTITY
      REAL(DOUBLE), INTENT(IN) :: MIN_OVERLAP
      CHARACTER(LEN=*), INTENT(IN) :: DETAIL
      CHARACTER(LEN=TRACE_FIELD_LENGTH) :: FIELDS(TRACE_FIELD_COUNT)

      CALL OPEN_ORBOPT_TRACE
      IF (.NOT.TRACE_OPEN) RETURN
      CALL CLEAR_TRACE_FIELDS(FIELDS, 'round_decision', NIT)
      CALL PUT_INTEGER(FIELDS(4), ROLLBACK_COUNT)
      CALL PUT_LOGICAL(FIELDS(59), ACCEPTED)
      CALL PUT_LOGICAL(FIELDS(60), ORDER_CHANGED)
      CALL PUT_LOGICAL(FIELDS(61), NONIDENTITY)
      CALL PUT_INTEGER(FIELDS(62), ROLLBACK_COUNT)
      CALL PUT_REAL(FIELDS(63), MIN_OVERLAP)
      FIELDS(40) = DETAIL
      CALL EMIT_TRACE_ROW(ORBOPT_TRACE_UNIT, FIELDS)
      END SUBROUTINE TRACE_ROUND_DECISION

      SUBROUTINE TRACE_LEVEL_ENERGY(NIT, LEVEL_INDEX, BLOCK_INDEX,  &
                                    LEVEL_SERIAL, ENERGY, WEIGHT)
      INTEGER, INTENT(IN) :: NIT, LEVEL_INDEX, BLOCK_INDEX, LEVEL_SERIAL
      REAL(DOUBLE), INTENT(IN) :: ENERGY, WEIGHT
      CHARACTER(LEN=TRACE_FIELD_LENGTH) :: FIELDS(TRACE_FIELD_COUNT)
      INTEGER :: TRACE_NIT
      CALL OPEN_ORBOPT_TRACE
      IF (.NOT.TRACE_OPEN) RETURN
      TRACE_NIT = NIT
      IF (TRACE_NIT == 0) TRACE_NIT = ORBOPT_ITERATION
      CALL CLEAR_TRACE_FIELDS(FIELDS, 'level_energy', TRACE_NIT)
      CALL PUT_INTEGER(FIELDS(4), LEVEL_INDEX)
      CALL PUT_INTEGER(FIELDS(5), BLOCK_INDEX)
      CALL PUT_INTEGER(FIELDS(6), LEVEL_SERIAL)
      CALL PUT_REAL(FIELDS(19), ENERGY)
      CALL PUT_REAL(FIELDS(50), WEIGHT)
      CALL EMIT_TRACE_ROW(ORBOPT_TRACE_UNIT, FIELDS)
      END SUBROUTINE TRACE_LEVEL_ENERGY

      SUBROUTINE TRACE_MPI_SUMMARY(NIT)
      INTEGER, INTENT(IN) :: NIT
      REAL(DOUBLE) :: LOCAL_SUMMARY(6), MIN_SUMMARY(6), MAX_SUMMARY(6)
      REAL(DOUBLE) :: SCALE
      CHARACTER(LEN=TRACE_FIELD_LENGTH) :: FIELDS(TRACE_FIELD_COUNT)
      CHARACTER(LEN=512) :: FILE_NAME
      INTEGER :: I, J, RANK_UNIT
      INTEGER(KIND=8) :: FILE_SIZE
      LOGICAL :: MISMATCH

      IF (.NOT.TRACE_ORBOPT) RETURN
      LOCAL_SUMMARY = 0.D0
      DO J = 1, NW
         LOCAL_SUMMARY(1) = LOCAL_SUMMARY(1) + DBLE(J)*E(J)
         LOCAL_SUMMARY(2) = LOCAL_SUMMARY(2) + DBLE(J)*SCNSTY(J)
         LOCAL_SUMMARY(5) = LOCAL_SUMMARY(5) + DBLE(J)*UCF(J)
         DO I = 1, MF(J)
            LOCAL_SUMMARY(3) = LOCAL_SUMMARY(3) + DBLE(I+J)*PF(I,J)
            LOCAL_SUMMARY(4) = LOCAL_SUMMARY(4) + DBLE(I+J)*QF(I,J)
         END DO
      END DO
      IF (ASSOCIATED(EVEC)) THEN
         DO I = 1, SIZE(EVEC)
            LOCAL_SUMMARY(6) = LOCAL_SUMMARY(6) + DBLE(I)*EVEC(I)
         END DO
      ENDIF
      CALL MPI_Allreduce(LOCAL_SUMMARY, MIN_SUMMARY, 6,             &
                         MPI_DOUBLE_PRECISION, MPI_MIN,             &
                         MPI_COMM_WORLD, ierr)
      CALL MPI_Allreduce(LOCAL_SUMMARY, MAX_SUMMARY, 6,             &
                         MPI_DOUBLE_PRECISION, MPI_MAX,             &
                         MPI_COMM_WORLD, ierr)
      MISMATCH = .FALSE.
      DO I = 1, 6
         SCALE = MAX(1.D0, ABS(MIN_SUMMARY(I)), ABS(MAX_SUMMARY(I)))
         IF (ABS(MAX_SUMMARY(I)-MIN_SUMMARY(I)) > 1.D-12*SCALE)    &
            MISMATCH = .TRUE.
      END DO
      IF (.NOT.MISMATCH) RETURN

      WRITE (FILE_NAME,'(A,I3.3,A)') 'orbopt_trace.rank', myid, '.csv'
      IF (LEN_TRIM(ORBOPT_TRACE_DIRECTORY) > 0) FILE_NAME =        &
         TRIM(ORBOPT_TRACE_DIRECTORY)//'/'//TRIM(FILE_NAME)
      INQUIRE(FILE=TRIM(FILE_NAME), SIZE=FILE_SIZE)
      OPEN(NEWUNIT=RANK_UNIT, FILE=TRIM(FILE_NAME), STATUS='UNKNOWN', &
           POSITION='APPEND', ACTION='WRITE')
      IF (FILE_SIZE <= 0) CALL WRITE_TRACE_HEADER(RANK_UNIT)
      DO J = 1, 6
         CALL CLEAR_TRACE_FIELDS(FIELDS, 'mpi_summary_mismatch', NIT)
         CALL PUT_INTEGER(FIELDS(6), J)
         CALL PUT_REAL(FIELDS(39), LOCAL_SUMMARY(J))
         WRITE (FIELDS(40),'(A,ES16.8,A,ES16.8)')                  &
            'min=', MIN_SUMMARY(J), ' max=', MAX_SUMMARY(J)
         CALL EMIT_TRACE_ROW(RANK_UNIT, FIELDS)
      END DO
      CLOSE(RANK_UNIT)
      END SUBROUTINE TRACE_MPI_SUMMARY

      SUBROUTINE CHECK_RELATIVISTIC_PAIRS
      INTEGER :: I, J, L, PARTNER_KAPPA
      LOGICAL :: UNBALANCED, PARTNER_FOUND
      CHARACTER(LEN=TRACE_FIELD_LENGTH) :: FIELDS(TRACE_FIELD_COUNT)

      UNBALANCED = .FALSE.
      DO I = 1, NW
         IF (NAK(I) > 0) THEN
            L = NAK(I)
            PARTNER_KAPPA = -(L + 1)
         ELSE
            L = -NAK(I) - 1
            IF (L == 0) CYCLE
            PARTNER_KAPPA = L
         ENDIF
         PARTNER_FOUND = .FALSE.
         DO J = 1, NW
            IF (NP(J) /= NP(I) .OR. NAK(J) /= PARTNER_KAPPA) CYCLE
            PARTNER_FOUND = .TRUE.
            IF (I > J) EXIT
            IF (LFIX(I) .EQV. LFIX(J)) EXIT
            UNBALANCED = .TRUE.
            IF (myid == 0 .AND. WARN_UNBALANCED_PAIR) THEN
               WRITE (ISTDE,'(A,1X,I0,A,1X,I0,A)')                 &
                  'ORBOPT warning: unbalanced relativistic pair', &
                  NP(I), NH(I), NP(J), NH(J)
            ENDIF
            IF (TRACE_ORBOPT .AND. myid == 0) THEN
               CALL OPEN_ORBOPT_TRACE
               CALL CLEAR_TRACE_FIELDS(FIELDS, 'pair_check', 0)
               CALL PUT_INTEGER(FIELDS(4), I)
               CALL PUT_INTEGER(FIELDS(5), J)
               FIELDS(40) = 'unbalanced_selection'
               CALL EMIT_TRACE_ROW(ORBOPT_TRACE_UNIT, FIELDS)
            ENDIF
            EXIT
         END DO
         IF (PARTNER_FOUND .OR. LFIX(I)) CYCLE
         UNBALANCED = .TRUE.
         IF (myid == 0 .AND. WARN_UNBALANCED_PAIR) THEN
            WRITE (ISTDE,'(A,1X,I0,A,1X,A,I0)')                    &
               'ORBOPT warning: varied orbital has no relativistic partner', &
               NP(I), NH(I), 'expected kappa=', PARTNER_KAPPA
         ENDIF
         IF (TRACE_ORBOPT .AND. myid == 0) THEN
            CALL OPEN_ORBOPT_TRACE
            CALL CLEAR_TRACE_FIELDS(FIELDS, 'pair_check', 0)
            CALL PUT_ORBITAL_FIELDS(FIELDS, I)
            WRITE (FIELDS(40),'(A,I0)') 'missing_partner_kappa=',  &
                                         PARTNER_KAPPA
            CALL EMIT_TRACE_ROW(ORBOPT_TRACE_UNIT, FIELDS)
         ENDIF
      END DO

      IF (UNBALANCED .AND. REQUIRE_BALANCED_PAIR) THEN
         IF (myid == 0) WRITE (ISTDE,'(A)')                        &
            'ORBOPT: set GRASP_REQUIRE_BALANCED_PAIR=0 to continue.'
         ERROR STOP 'ORBOPT: unbalanced relativistic orbitals selected'
      ENDIF
      END SUBROUTINE CHECK_RELATIVISTIC_PAIRS

      END MODULE ORBOPT_TRACE_C
